#!/bin/bash

## Logs are formatted as clamscan-category-YYYYMMDD_HHMM.log
# This directory is where manual scans will output their logfiles. Requires full path! (e.g. no ~ for home)
SCAN_LOG_DIR="/var/log/clamav"
# How many log files to preserve before deleting old ones. A full scan generates 10 logfiles.
MAX_LOGS=20
# Name of logfile, will be generated at scan time
LOGFILE=""
# List of all logs generated by current scan
declare -a LOG_LIST
# This will hold the timestamp the scan started at, generated when user selects scan type.
TIMESTAMP=""
# This will hold the arguments passed through to clamscan based on the user's selection
SCAN_ARGS=""

setTimestamp() {
	TIMESTAMP=$(date "+%Y%m%d_%H%M")
}

setLogFile() {
	logName=$1
	LOGFILE="${SCAN_LOG_DIR}/clamscan-${logName}-${TIMESTAMP}.log"
	LOG_LIST+=("$LOGFILE")
}


setOutputLevel() {
	selection=$1

	if [[ ${selection} == "1" ]]; then
                SCAN_ARGS='-ri'
	elif [[ ${selection} == "2" ]]; then
                SCAN_ARGS='-r'
        else
                echo "Received unexpected output selection. Exiting..."
                exit 1
        fi
}

errorCheck() {
	retCode=$1
	dirTarget=$2 
	scanName=$3

	if [[ ${retCode} -ne 0 ]]; then
		printf "\nVirus scanning ${dirTarget} returned something unexpected!\n"
		read -n 1 -s -r -p "Press any key to exit..."
		exit 1
	fi

	printf "\n${scanName} scan completed without issue!\n"
}

cleanLogs() {
	logCount=$(ls -1q ${SCAN_LOG_DIR}/*.log 2>/dev/null | wc -l)

	if [[ ${logCount} -ge ${MAX_LOGS} ]]; then
		echo "Deleting oldest log file to avoid exceeding maximum number of logs (${MAX_LOGS})..."
		stat --printf='%Y %n\0' ${SCAN_LOG_DIR}/* | sort -zn | sed -z 's/[^ ]\{1,\} //;q' | xargs -r0 rm
		if [[ $? -ne 0 ]]; then
			echo "Something unexpected happened while cleaning up log files."
			echo "Exiting..."
			exit 1
		fi
	fi
}

scan(){
	scanTarget=$1
	scanName=$2
	logName=$3

	cleanLogs
	setLogFile $logName

	printf "\nLog will be saved to ${LOGFILE}\n"
	printf "\nBeginning scan of ${scanName}...\n"

	clamscan $SCAN_ARGS $scanTarget | tee ${LOGFILE}
	errorCheck $? "$scanTarget" "$scanName"
}

scanDownloads() {
	scan '/home/*/Downloads' 'Downloads' 'download'
}

scanHome() {
	scan '/home/' 'Home Folders' 'home'
}

scanSystem() {
	printf "\nBeginning scan of system files (this will produce a number of scans)...\n"

	scan '/etc/' 'Core System Folder' 'core'
	
	scan '/tmp/' 'Temporary System Folder' 'temp'

	scan '/var/tmp' 'Variable Temporary System Folder' 'tempsys'

	scan '/opt/' 'Optional System Folder' 'opt'

	scan '/srv/' 'System Web Folder' 'sysweb'

	scan '/bin/' 'Binaries Folder' 'bin'

	scan '/sbin/' 'System Binaries Folder' 'sysbin'

	scan '/usr/local/bin' 'User Binaries Folder' 'userbin'

	printf "\nAll system scans completed successfully!\n"

}

scanMount() {
	scan '/run/media' 'Mounted Drives' 'mount'
}

scanAll() {
	printf "\nScanning everything (this will likely take days!)...\n"

	scanHome
	scanSystem
	scanMount
}

if [[ $EUID -ne 0 ]]; then
	printf "This script needs root permissions to update/install ClamAV and run scans!\n"
	printf "Exiting...\n"
	sleep 2
	exit 1
fi

echo "Checking to make sure ClamAV is installed..."

needsInstall=false

packages=("clamav" "clamav-freshclam" "clamd")
for package in ${packages[@]}; do
	rpm -q ${package} &> /dev/null
	checkInstalled=$?

	if [[ ${checkInstalled} == 1 ]]; then
		echo "${package} package is not installed!"
		needsInstall=true
	fi
done


if [[ ${needsInstall} == true ]]; then
	echo "Core components of ClamAV are missing!"
	while true; do
		read -p "Do you wish to install ClamAV? [Y/N] " yesno
		case $yesno in
			[Yy]* ) break;;
			[Nn]* ) echo "User opted not to install, exiting..."; sleep 2; exit 1;;
			* ) echo "Please answer Y or N.";;
		esac
	done

	dnf install -y clamav clamav-update clamd

	if [[ $? -ne 0 ]]; then
		echo "Installing ClamAV failed!"
		echo "Exiting..."
		sleep 2
		exit 1
	fi
fi

echo "ClamAV is installed!"

echo "Updating ClamAV definitions!"
freshclam

if [[ $? -ne 0 ]]; then
	echo "Udpating virus definitions failed!"
	echo "Exiting..."
	sleep 5
	exit 1
fi

echo "Definitions updated."

if [[ ! -d "${SCAN_LOG_DIR}" ]]; then
	echo "Log file directory not found. Creating..."
	mkdir -p ${SCAN_LOG_DIR}
	if [[ $? -ne 0 ]]; then
		echo "Failed to create log directory! Exiting..."
	fi
	echo "Successfully created directory for scan logs."
fi

echo "Scans will be logged to ${SCAN_LOG_DIR}"

while true; do
	printf "\nPlease select output. This will also control what shows in log files:\n"
	echo "[1] Infected files only"
	echo "[2] All scanned files"
	read -p "What level of output would you like? [1 or 2]: " logSelector
	case $logSelector in
		[1]* ) setOutputLevel $logSelector; break;;
		[2]* ) setOutputLevel $logSelector; break;;
		* ) echo "Please choose 1 or 2.";;
	esac
done

while true; do
	printf "\nPlease select a scan:\n"
	echo "[1] Scan Downloads"
	echo "[2] Scan home folders"
	echo "[3] Scan system folders"
	echo "[4] Scan all drives mounted in /run/media/ (Slow!)"
	echo "[5] Scan everything (VERY slow!)"
	read -p "What scan would you like? [1, 2, 3, 4, or 5]: " scanSelector
	case $scanSelector in
		[1]* ) setTimestamp; scanDownloads; break;;
		[2]* ) setTimestamp; scanHome; break;;
		[3]* ) setTimestamp; scanSystem; break;;
		[4]* ) setTimestamp; scanMount; break;;
		[5]* ) setTimestamp; scanAll; break;;
		* ) echo "Please choose 1, 2, 3, 4, or 5.";;
	esac
done


printf "\nAll scans completed!\n"

printf "\nLog files created by scan:\n"

for log in "${LOG_LIST[@]}"; do
	   echo "$log"
done

read -n 1 -s -r -p "Press any key to exit..."
printf "\n"
exit 0
